Models/DB/Player.cs
namespace GymBusiness.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Player")]
    public partial class Player
    {
        
        public int ID { get; set; }

        [Required]
        [StringLength(50)]
        public string Full_Name { get; set; }

        [Required]
        [StringLength(50)]
        public string Mail { get; set; }

        [Required]
        [StringLength(50)]
        public string Mobile { get; set; }

        [Column(TypeName = "date")]
        public DateTime Date_Of_Birth { get; set; }

        [StringLength(128)]
        [ForeignKey("Coach")]
        public string Coach_Id { get; set; }
        public ApplicationUser Coach { get; set; }
        public virtual ICollection<History_for_player> History_for_player { get; set; }

        public virtual ICollection<Media> Media { get; set; }
    }
}

Controllers/History_for_playerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GymBusiness.Models;
using GymBusiness.Models.ViewModels;
using Newtonsoft.Json;

namespace GymBusiness.Controllers
{
    //[Authorize]
    public class History_for_playerController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: History_for_player
        public ActionResult Index()
        {
            HistoryPlayersLoadsVM vm=new HistoryPlayersLoadsVM();
            var history_for_player = db.History_for_player.Include(h => h.Load).Include(h => h.Player);
            return View(history_for_player.ToList());
        }

        // GET: History_for_player/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            History_for_player history_for_player = db.History_for_player.Find(id);
            if (history_for_player == null)
            {
                return HttpNotFound();
            }
            return View(history_for_player);
        }

        // GET: History_for_player/Create
        public ActionResult Create()
        {
            ViewBag.Loads_id = new SelectList(db.Loads, "ID", "ID");
            ViewBag.Players = new SelectList(db.Players, "ID", "Full_Name");
            return View();
        }

        // POST: History_for_player/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( HistoryPlayersLoadsVM history)
        {
            if (ModelState.IsValid)
            {
                db.Loads.Add(history.L);
                if (db.SaveChanges() > 0)
                {
                    history.H.Loads_id = history.L.ID;
                    db.History_for_player.Add(history.H);
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }

            //ViewBag.Loads_id = new SelectList(db.Loads, "ID", "ID", history_for_player.Loads_id);
            ViewBag.Player_id = new SelectList(db.Players, "ID", "Full_Name", history.H.Player_id);
            return View(history);
        }

        // GET: History_for_player/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            History_for_player history_for_player = db.History_for_player.Find(id);
            if (history_for_player == null)
            {
                return HttpNotFound();
            }
            ViewBag.Loads_id = new SelectList(db.Loads, "ID", "ID", history_for_player.Loads_id);
            ViewBag.Player_id = new SelectList(db.Players, "ID", "Full_Name", history_for_player.Player_id);
            return View(history_for_player);
        }

        // POST: History_for_player/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Datetime,Player_id,Weight,Loads_id")] History_for_player history_for_player)
        {
            if (ModelState.IsValid)
            {
                db.Entry(history_for_player).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Loads_id = new SelectList(db.Loads, "ID", "ID", history_for_player.Loads_id);
            ViewBag.Player_id = new SelectList(db.Players, "ID", "Full_Name", history_for_player.Player_id);
            return View(history_for_player);
        }

        // GET: History_for_player/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            History_for_player history_for_player = db.History_for_player.Find(id);
            if (history_for_player == null)
            {
                return HttpNotFound();
            }
            return View(history_for_player);
        }
        public ActionResult Reports(int id)
        {
            ChartVM vm = new ChartVM();
            vm.ID = id;
            ViewBag.Playername = db.Players.Find(id).Full_Name;
            return View(vm);
        }

        public ActionResult History(int id)
        {
            ChartVM vm = new ChartVM();
            ViewBag.Playername = db.Players.Find(id).Full_Name;
            vm.History = db.History_for_player.OrderBy(a => a.Datetime).Where(a => a.Player_id == id).ToList();
            return View(vm);
        }
        //public ContentResult JSON(int id)
        //{
        //    //List<History_for_player> dataPoints = new List<History_for_player>();
        //    //Random random = new Random();
        //    //double y = yStart;

        //    //for (int i = 0; i < length; i++)
        //    //{
        //    //    y = y + random.Next(-1, 2);
        //    //    dataPoints.Add(new History_for_player());
        //    //}
        //    ChartVM vm = new ChartVM();
        //    var data = db.History_for_player.Where(x => x.Player_id == id).ToList();
        //    List<int> Days = new List<int>();
        //    var weight = data.Select(a => a.Weight).Distinct().ToList();
        //    foreach (var item in weight)
        //    {
        //        Days.Add(data.Count(a => a.Weight == item));
        //    }
        //    vm.Dayes = Days;
        //    vm.Weight = weight;
        //    return Content(JsonConvert.SerializeObject(vm, _jsonSetting), "application/json");
        //}

        //JsonSerializerSettings _jsonSetting = new JsonSerializerSettings() { NullValueHandling = NullValueHandling.Ignore };
        // POST: History_for_player/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            History_for_player history_for_player = db.History_for_player.Find(id);
            db.History_for_player.Remove(history_for_player);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        public ContentResult JSON(int playerid)
        {
            var playerhistory=db.History_for_player.Where(x=>x.Player_id== playerid).OrderBy(x => x.Datetime);
            //leghnth
            int DayesCount = playerhistory.Count();
            //Dayes
          
            
            var Wights = playerhistory.Select(xxx=>xxx.Weight).ToList();
            
            List<DataPoint> dataPoints = new List<DataPoint>();
            for (int i = 1; i <= DayesCount; i++)
            {
                dataPoints.Add(new DataPoint(i, Wights[i-1]));


            }

            return Content(JsonConvert.SerializeObject(dataPoints, _jsonSetting), "application/json");
        }

        JsonSerializerSettings _jsonSetting = new JsonSerializerSettings() { NullValueHandling = NullValueHandling.Ignore };

    

    protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/PlayersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GymBusiness.Models;

namespace GymBusiness.Controllers
{
    [Authorize]
    public class PlayersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Players
        public ActionResult Index()
        {
            var players = db.Players.Include(p => p.Coach);
            return View(players.ToList());
        }

        // GET: Players/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Player player = db.Players.Find(id);
            if (player == null)
            {
                return HttpNotFound();
            }
            return View(player);
        }

        // GET: Players/Create
        public ActionResult Create()
        {
            ViewBag.Coach_Id = new SelectList(db.Users, "Id", "Email");
            return View();
        }

        // POST: Players/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Full_Name,Mail,Mobile,Date_Of_Birth,Coach_Id")] Player player)
        {
            if (ModelState.IsValid)
            {
                db.Players.Add(player);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Coach_Id = new SelectList(db.Users, "Id", "Email", player.Coach_Id);
            return View(player);
        }

        // GET: Players/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Player player = db.Players.Find(id);
            if (player == null)
            {
                return HttpNotFound();
            }
            ViewBag.Coach_Id = new SelectList(db.Users, "Id", "Email", player.Coach_Id);
            return View(player);
        }

        // POST: Players/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Full_Name,Mail,Mobile,Date_Of_Birth,Coach_Id")] Player player)
        {
            if (ModelState.IsValid)
            {
                db.Entry(player).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Coach_Id = new SelectList(db.Users, "Id", "Email", player.Coach_Id);
            return View(player);
        }

        // GET: Players/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Player player = db.Players.Find(id);
            if (player == null)
            {
                return HttpNotFound();
            }
            return View(player);
        }

        // POST: Players/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Player player = db.Players.Find(id);
            try
            {
               var history= db.History_for_player.Where(a => a.Player_id == id).ToList();
                if(history.Count()>0)
                {
                    foreach (var item in history)
                    {
                        db.History_for_player.Remove(item);
                        
                        db.SaveChanges();
                    }
                }
                var media=db.Media.Where(a => a.Player_id == id).ToList();
                if (media.Count()>0)
                {
                    foreach (var item in media)
                    {
                        db.Media.Remove(item);

                        db.SaveChanges();
                    }
                }
            }
            catch
            {
                return RedirectToAction("Index");
            }
            db.Players.Remove(player);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Players/Create.cshtml
@model GymBusiness.Models.Player

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Player</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Full_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Full_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Full_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mobile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date_Of_Birth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date_Of_Birth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date_Of_Birth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Coach_Id, "Coach_Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Coach_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Coach_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Players/Delete.cshtml
@model GymBusiness.Models.Player

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Player</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Coach.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Coach.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Full_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Full_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mobile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mobile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_Of_Birth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_Of_Birth)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Players/Details.cshtml
@model GymBusiness.Models.Player

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Player</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Coach.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Coach.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Full_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Full_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mobile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mobile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_Of_Birth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_Of_Birth)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Players/Edit.cshtml
@model GymBusiness.Models.Player

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Player</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Full_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Full_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Full_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mobile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date_Of_Birth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date_Of_Birth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date_Of_Birth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Coach_Id, "Coach_Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Coach_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Coach_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Players/Index.cshtml
@model IEnumerable<GymBusiness.Models.Player>

@{
    ViewBag.Title = "Players";
 
}
    <link href="~/Content/Datatable.css" rel="stylesheet" />
<h2 class="tName">Players</h2>

<p>
    @Html.ActionLink("Create New", "Create", null, new { @class = "mb-2 btn btn-info bcreate" })
</p>
<table class="table" id="Table">
    <thead>

    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Coach.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Full_Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Mail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Mobile)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date_Of_Birth)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Coach.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Full_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mobile)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date_Of_Birth)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("PlayerChart", "Reports", "History_for_player", new { id = item.ID }, null) |
                @Html.ActionLink("PlayerHistory", "History", "History_for_player", new { id = item.ID }, null) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

    </tbody>
</table>
@section scripts{
    <script src="~/Scripts/Datatable1.js"></script>
    <script src="~/Scripts/Datatable2.js"></script>
    <script>
        $(document).ready(function () {
            $('#Table').DataTable();
            $("#Table_info").text("");
        });
    </script>
}