Models/DB/Media.cs
namespace GymBusiness.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Media
    {
        public int ID { get; set; }

        [Required]
        public string Media_Path { get; set; }
        [ForeignKey("Player")]

        public int? Player_id { get; set; }

        [StringLength(128)]
        [ForeignKey("Coach")]

        public string Coach_id { get; set; }

        public virtual Player Player { get; set; }

        public ApplicationUser Coach { get; set; }
    }
}

Controllers/MediaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GymBusiness.Models;
using GymBusiness.Models.ViewModels;

namespace GymBusiness.Controllers
{
    [Authorize]
    public class MediaController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Media
        public ActionResult Index()
        {
            var media = db.Media.Include(m => m.Coach).Include(m => m.Player);
            return View(media.ToList());
        }

        // GET: Media/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Media media = db.Media.Find(id);
            if (media == null)
            {
                return HttpNotFound();
            }
            return View(media);
        }
        

        // GET: Media/Create
        public ActionResult Create()
        {
            ViewBag.Coach_id = new SelectList(db.Users, "Id", "Email");
            ViewBag.Player_id = new SelectList(db.Players, "ID", "Full_Name");
            return View();
        }

        // POST: Media/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( MediaVM media)
        {
            if (ModelState.IsValid)
            {
                Media m = new Media();
                string path = Server.MapPath("~/images/");
                media.Media_Path.SaveAs(path + media.Media_Path.FileName);
                m.Media_Path = media.Media_Path.FileName;
                m.Coach_id = media.Coach_id;
                m.Player_id = media.Player_id;
                db.Media.Add(m);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Coach_id = new SelectList(db.Users, "Id", "Email", media.Coach_id);
            ViewBag.Player_id = new SelectList(db.Players, "ID", "Full_Name", media.Player_id);
            return View(media);
        }

        // GET: Media/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Media media = db.Media.Find(id);
            if (media == null)
            {
                return HttpNotFound();
            }
            ViewBag.Coach_id = new SelectList(db.Users, "Id", "Email", media.Coach_id);
            ViewBag.Player_id = new SelectList(db.Players, "ID", "Full_Name", media.Player_id);
            return View(media);
        }

        // POST: Media/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Media_Path,Player_id,Coach_id")] Media media)
        {
            if (ModelState.IsValid)
            {
                db.Entry(media).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Coach_id = new SelectList(db.Users, "Id", "Email", media.Coach_id);
            ViewBag.Player_id = new SelectList(db.Players, "ID", "Full_Name", media.Player_id);
            return View(media);
        }

        // GET: Media/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Media media = db.Media.Find(id);
            if (media == null)
            {
                return HttpNotFound();
            }
            return View(media);
        }

        // POST: Media/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Media media = db.Media.Find(id);
            db.Media.Remove(media);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Media/Create.cshtml
@model GymBusiness.Models.ViewModels.MediaVM

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create","Media",FormMethod.Post,new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Media</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Media_Path, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Media_Path, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Media_Path, "", new { @class = "text-danger" })*@
                <input type='file'  id='fileUpload' name="Media_Path" class="form-control"/>
                @Html.ValidationMessageFor(model => model.Media_Path, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Player_id, "Player Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(a=>a.Player_id, ViewBag.Player_id as SelectList,"--Chosee Player", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Player_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Coach_id, "Coach Email", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(a=>a.Coach_id, ViewBag.Coach_id as SelectList,"--Chosee Cach", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Coach_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    $(function () {
    $('#fileUpload').fileupload({
    dataType: 'json',
    done: function (e, data) {
    $.each(data.result.files, function (index, file) {
    $('
    <p />').text(file.name).appendTo(document.body);
    });
    }
    });
    });
}

Views/Media/Delete.cshtml
@model GymBusiness.Models.Media

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Media</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Coach.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Coach.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Player.Full_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Player.Full_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Media_Path)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Media_Path)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Media/Details.cshtml
@model GymBusiness.Models.Media

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Media</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Coach.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Coach.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Player.Full_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Player.Full_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Media_Path)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Media_Path)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Media/Edit.cshtml
@model GymBusiness.Models.Media

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Media</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Media_Path, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Media_Path, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Media_Path, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Player_id, "Player_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Player_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Player_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Coach_id, "Coach_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Coach_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Coach_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Media/Index.cshtml
@model IEnumerable<GymBusiness.Models.Media>

@{
    ViewBag.Title = "Media";
}
<link href="~/Content/Datatable.css" rel="stylesheet" />
<h2 class="tName">Media</h2>

<p>
    @Html.ActionLink("Create New", "Create", null, new { @class = "mb-2 btn btn-info bcreate" })
</p>
<table class="table" id="Table">
    <thead>

    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Coach.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Player.Full_Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Media_Path)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Coach.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Player.Full_Name)
            </td>
            <td>
                @{
                    var arr = item.Media_Path.Split('.');
                    var last = arr.Last().ToString();
                    if (last == "jpeg" || last == "png" || last == "jpg" || last == "gif")
                    {
                        <img src="~/images/@item.Media_Path" style="width:100px;height:100px;" />

                    }
                    else
                    {
                        <video width="100" height="100" controls>
                            <source src="~/images/@item.Media_Path" type="video/mp4">
                            <source src="~/images/@item.Media_Path" type="video/ogg">
                            
                        </video>
                    }
                }
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

    </tbody>
</table>
@section scripts{
    <script src="~/Scripts/Datatable1.js"></script>
    <script src="~/Scripts/Datatable2.js"></script>
    <script>
        $(document).ready(function () {
            $('#Table').DataTable();
            $("#Table_info").text("");
        });
    </script>
}